server:
  port: ${SERVER_PORT:8085}
spring:
  application:
    name: inventory-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5437/inventory_db}
    username: ${DB_USERNAME:commerceflow}
    password: ${DB_PASSWORD:}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/auth/.well-known/jwks.json}
          issuer-uri: ${JWT_ISSUER:http://localhost:8080/api/v1/auth}
commerceflow:
  inventory:
    demo-seed: ${INVENTORY_DEMO_SEED:false}
management:
  endpoints:
    web:
      exposure:
        include: health,info
