server:
  port: ${SERVER_PORT:8084}
spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/order_db}
    username: ${DB_USERNAME:commerceflow}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/auth/.well-known/jwks.json}
          issuer-uri: ${JWT_ISSUER:http://localhost:8080/api/v1/auth}
commerceflow:
  catalog-url: ${CATALOG_SERVICE_URL:http://localhost:8083}
management:
  endpoints:
    web:
      exposure:
        include: health,info
